### ISSUE TITLE
i get error

### ISSUE THREAD

**Issue by 503945930** [WebbyLab/itsquiz-wall#138]
npm run nodemon

![qq 20160706163405](https://cloud.githubusercontent.com/assets/8409001/16612068/8ff91738-4397-11e6-964c-27e0944bb520.png)

**Comment by artemT82** [comment]
Here is a corresponding stackoverflow question http://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf. You can fix it quite easily. Hope it'll help

**Comment by koorchik** [comment]
Please, reopen if the issue still exists.
