### ISSUE TITLE
Get rid of babel-node

### ISSUE THREAD

**Issue by amok** [WebbyLab/itsquiz-wall#14]
[babel-node not meant for production use](https://babeljs.io/docs/usage/cli/#babel-node)
maybe it's appropriate to transpile server side sources like [here](https://github.com/babel/babel/blob/master/Gulpfile.js#L14-L35)

**Comment by koorchik** [comment]
We know it. It this really small app and startup performance pernalty is not a problem for us.

**Comment by koorchik** [comment]
There is another convinient option - require hook. 
```
require("babel-core/register");
```

Bu I guess that it has all the performance issues that babel-node has

**Comment by amok** [comment]
you're right
babel-node - https://github.com/babel/babel/blob/master/packages/babel-cli/src/_babel-node.js#L57-L70
babel-register - https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L103-L109

**Comment by koorchik** [comment]
Just replaced babel-node with require("babel-core/register"); A little bit better with memory usage and no additional proccess.
