### ISSUE TITLE
Failed to compile but it runs

### ISSUE THREAD

**Issue by mapyourown** [WebbyLab/itsquiz-wall#206]
I cloned the app and I am getting error compiling the js, it is complaining the for loop in the reducer, activation.js from line 31- 37 and I rewrite using foreach lodash function
         import { forEach } from 'lodash/collection;
          forEach(newActivations, (value, key) => {
                if (action.offset + key < loadedActivations.length) {
                    loadedActivations[action.offset + key] = newActivations[key];
                } else {
                    loadedActivations.push(newActivations[key]);
                }
            });
The error disappear and compiled successfully, not sure I am doing correctly but it working fine. May be it helps someone who cloning this app.

**Comment by yaDaryStil** [comment]
Hey there, I've tried to run the project recently and everything went just fine in my case. We will give this problem a more close look if someone else would encounter it. For now, thanks for your report and I'm closing the issue, indeed maybe it will help someone
