### ISSUE TITLE
both server side and client side making API call

### ISSUE THREAD

**Issue by abhijeetNmishra** [WebbyLab/itsquiz-wall#28]
after server side is doing fetchData, client side also dispatching the action and react component is getting re rendered. Any idea even if redux state is not changing, react dom is getting re rendered ?

Also in your code base, react-router and history modules seems to be out of sync.

**Comment by koorchik** [comment]
Yes, we refetch data for simpilcity, it can be ommited by addional checks. But in our case this is not an issue, React applies virual DOM diffing algoritm and does not touch DOM.

**Comment by koorchik** [comment]
Thanks, will check the react-router and history modules
