### ISSUE TITLE
nodemon: not found

### ISSUE THREAD

**Issue by brw31415** [WebbyLab/itsquiz-wall#41]
npm run nodemon

> itsquiz-wall@0.0.1 nodemon /home/brw314/react/itsquiz-wall                                             
> nodemon --exec babel-node -- server/runner.js                                                          
                                                                                                         
sh: 1: nodemon: not found

npm ERR! Linux 4.1.0-insomnia247
npm ERR! argv "/home/brw314/.node_local/bin/node" "/home/brw314/.node_local/bin/npm" "run" "nodemon"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! itsquiz-wall@0.0.1 nodemon: `nodemon --exec babel-node -- server/runner.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the itsquiz-wall@0.0.1 nodemon script 'nodemon --exec babel-node -- server/runner.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the itsquiz-wall package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon --exec babel-node -- server/runner.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls itsquiz-wall
npm ERR! There is likely additional logging output above.

0 info it worked if it ends with ok                                                                      
1 verbose cli [ '/home/brw314/.node_local/bin/node',                                                     
1 verbose cli   '/home/brw314/.node_local/bin/npm',                                                      
1 verbose cli   'run',                                                                                   
1 verbose cli   'nodemon' ]                                                                              
2 info using npm@3.3.12                                                                                  
3 info using node@v5.1.0                                                                                 
4 verbose run-script [ 'prenodemon', 'nodemon', 'postnodemon' ]                                          
5 info lifecycle itsquiz-wall@0.0.1~prenodemon: itsquiz-wall@0.0.1                                       
6 silly lifecycle itsquiz-wall@0.0.1~prenodemon: no script for prenodemon, continuing                    
7 info lifecycle itsquiz-wall@0.0.1~nodemon: itsquiz-wall@0.0.1                                          
8 verbose lifecycle itsquiz-wall@0.0.1~nodemon: unsafe-perm in lifecycle true                            
9 verbose lifecycle itsquiz-wall@0.0.1~nodemon: PATH: /home/brw314/.node_local/lib/node_modules/npm/bin/n
ode-gyp-bin:/home/brw314/react/itsquiz-wall/node_modules/.bin:/home/brw314/.nvm:/home/brw314/code/go/bin:
/home/brw314/opt/java/jdk1.8.0_45/bin:/home/brw314/opt/java/jdk1.8.0_45/jre/bin:/home/brw314/.meteor:/hom
e/brw314/.node_local/bin:/home/brw314/.npm/bin:/home/brw314/.npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/lo
cal/games:/usr/games:/home/brw314/clj:/home/brw314/bin/go/bin:/home/brw314/bin/go/bin                    
10 verbose lifecycle itsquiz-wall@0.0.1~nodemon: CWD: /home/brw314/react/itsquiz-wall                    
11 silly lifecycle itsquiz-wall@0.0.1~nodemon: Args: [ '-c', 'nodemon --exec babel-node -- server/runner.
js' ]                                                                                                    
12 info lifecycle itsquiz-wall@0.0.1~nodemon: Failed to exec nodemon script                              
13 verbose stack Error: itsquiz-wall@0.0.1 nodemon: `nodemon --exec babel-node -- server/runner.js`      
13 verbose stack spawn ENOENT                                                                            
13 verbose stack     at ChildProcess.<anonymous> (/home/brw314/.node_local/lib/node_modules/npm/lib/utils
/spawn.js:17:16)                                                                                         
13 verbose stack     at emitTwo (events.js:87:13)                                                        
13 verbose stack     at ChildProcess.emit (events.js:172:7)                                              
13 verbose stack     at maybeClose (internal/child_process.js:818:16)                                    
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)            
14 verbose pkgid itsquiz-wall@0.0.1                                                                      
15 verbose cwd /home/brw314/react/itsquiz-wall                                                           
16 error Linux 4.1.0-insomnia247                                                                         
17 error argv "/home/brw314/.node_local/bin/node" "/home/brw314/.node_local/bin/npm" "run" "nodemon"     
18 error node v5.1.0                                                                                     
19 error npm  v3.3.12                                                                                    
20 error file sh                                                                                         
21 error code ELIFECYCLE                                                                                 
22 error errno ENOENT                                                                                    
23 error syscall spawn                                                                                   
24 error itsquiz-wall@0.0.1 nodemon: `nodemon --exec babel-node -- server/runner.js`                     
24 error spawn ENOENT                                                                                    
25 error Failed at the itsquiz-wall@0.0.1 nodemon script 'nodemon --exec babel-node -- server/runner.js'.
25 error Make sure you have the latest version of node.js and npm installed.                             
25 error If you do, this is most likely a problem with the itsquiz-wall package,                         
25 error not with npm itself.                                                                            
25 error Tell the author that this fails on your system:                                                 
25 error     nodemon --exec babel-node -- server/runner.js                                               
25 error You can get their info via:                                                                     
25 error     npm owner ls itsquiz-wall                                                                   
25 error There is likely additional logging output above.

**Comment by koorchik** [comment]
Cannot reproduce. Maybe you forgot to run "npm install" before runnning "npm run nodemon"?

**Comment by brw31415** [comment]
sorry! i was just about to cancel that...my fault... but thanks for your
fast response and thank you for posting such a professional level project!

**Comment by koorchik** [comment]
not a problem :)

**Comment by brw31415** [comment]
does the repo actually have functionality, because when i run it i can't
seem to login or anything, nothing is clickable, etc

**Comment by krambertech** [comment]
Have you copied a config file?
```
cp etc/client-config.json.sample etc/client-config.json
```

**Comment by brw31415** [comment]
yes, and this is all i see,pretty faces ;-)

http://80.112.131.85:5030/activations
