### ISSUE TITLE
Any Tests for the project?

### ISSUE THREAD

**Issue by khanghoang** [WebbyLab/itsquiz-wall#42]
Hi guys,
I think you guys do the great job for far. 
I just wonder how you guys do tests in this project?

**Comment by koorchik** [comment]
Hello @khanghoang. Thank you :)

As for tests, 99% of bugs (in "itsquiz-wall") are related to the visual issues (different browsers, different phones etc) and they can be tested only manually. At this moment, unit tests of React components does not make sense for this projects. We use eslint checking and the project is covered with selenium tests. But all the selenium tests (including "itsquiz-wall" tests) are in a private repo. We cannot opensource them as they coupled with other subsystems but I can say that we use [nightwatchjs](http://nightwatchjs.org/). It is a really great wrapper around selenium. 

Moreover, we plan to add unit tests to reducers but there will be nothing special - mocha, chai, isparta.
