### ISSUE TITLE
href for SEO?

### ISSUE THREAD

**Issue by christiansakai** [WebbyLab/itsquiz-wall#44]
Hi,

Thank you so much for open sourcing this repo and explaining it along! I definitely learned a not from this repo.

When I try to disable JavaScript in the browser and clicking one of the link, it doesn't go through the link, because there is no href attribute in the UI.  I'm just wondering how does this play out in being SEO friendly?

**Comment by koorchik** [comment]
Hello, @christiansakai 
It's very good point. In our case, we only need quiz's page sharing/indexing. But indeed href attribute will allow googlebot to crawl deeper. We will add it to our links.
