### ISSUE TITLE
Profile page not properly aligned when mobile

### ISSUE THREAD

**Issue by RaulTsc** [WebbyLab/itsquiz-wall#54]
Hello,

The Profile page is not properly aligned for mobile devices. I'd be happy to send a PR for this if that's fine.

http://imgur.com/tw9Dxxm

Raul

**Comment by RaulTsc** [comment]
Yeah... apparently I can't do that because the code is not there. When I wrote this I was at work and couldn't run it locally, but then I got home, ran it and saw that this is the code only for the Wall part of the app, guess that's why it's called itsquiz-wall :). Nonetheless, you should look into that.

**Comment by koorchik** [comment]
Yeah, only quiz wall (isomorphic app) is opensourced. Thanks a lot for the feedback, we are working on better mobile platforms support.

**Comment by koorchik** [comment]
@krambertech please, look at this!

**Comment by krambertech** [comment]
Looking better now
